version: '3'
services:
  tests:
    image: aaronmwilliams/python-api-testing
    depends_on:
      - "api"
    command: ["./wait-for-api.sh"]
  api:
    image: aaronmwilliams/user-exercises-rest
    ports:
      - 8080:8080
